@tool
# SPDX-FileCopyrightText: 2026 Frank Winter <https://www.frankwinter.com/>
# SPDX-License-Identifier: MIT
#
# This file was generated by Low Poly Colorizer (LPC). <https://github.com/wasdcat/low-poly-colorizer>
# A WASDCAT Games project. <https://www.wasdcat.com/>

class_name LpcSinglecolorResource
extends Resource

## One named look for the lpc_singlecolor material (Godot 4): a palette
## cell, a preset, and an optional emission override -- exactly the four
## per-instance values that shader takes.
##
## Save looks as .tres files ("Gold", "SignalRed", ...) and hand them around
## like any other resource: a signal node with a `stop` and a `go` slot calls
## [method apply_to] on its lamp whenever it switches.
##
## These are [b]instance[/b] uniforms -- they live on the MeshInstance3D, not
## on the material, which is why every instance can show a different look while
## they all share the one lpc_singlecolor.tres. [method apply_to] takes
## the node for that reason, and there is deliberately nothing here that touches
## the material: writing into it would change the look of every instance using
## it, and this script holds no reference to it at all, so it stays independent
## of where the exported files end up in your project.
##
## Regenerated on every export -- do not edit. The .tres files you author from
## it are yours and are never touched.


## The presets as they existed at the last export, by list position -- the
## value the shader's `lpc_preset_position` takes.
##
## Re-exporting after adding, deleting or [b]reordering[/b] presets rewrites
## this block. Code written against a member name ([code]Preset.EMISSION[/code])
## follows the change automatically; an already-authored .tres stores the plain
## int, so a reorder silently repoints it at whatever preset now sits at that
## position. Renaming is safe either way.
enum Preset {
	SOLID = 0,
	METALLIC = 1,
	CLEARCOAT = 2,
	EMISSION = 3,
}


## The palette parameters as they stood at the last export -- the full input
## to [method color_at], which reproduces any cell's color from them rather
## than reading the exported lpc_palette.png back. That keeps this
## script free of references to the other exported files, for the same reason
## [method apply_to] holds no reference to the material.
##
## Public on purpose: anything else that needs to reason about the palette
## (a swatch grid, a "nearest cell to this color" lookup, an editor tool)
## should build on these instead of hard-coding a second copy.
##
## Re-exporting after a palette change rewrites this block. Already-authored
## .tres files keep their cell coordinates and simply take on the new color
## there -- exactly what happens to the painted meshes.

## Total columns, including the greyscale column when there is one -- the
## bound [member palette_cell_x] is clamped to.
const PALETTE_COLS: int = 17

## Rows in the grid, top (lightest) to bottom (darkest).
const PALETTE_ROWS: int = 9

## Whether column 0 is a white-to-black ramp instead of a hue. The remaining
## columns are the hues, so this also says how much of the grid's width is not
## part of the color wheel.
const PALETTE_HAS_GREYSCALE: bool = true

## Saturation of the middle row (the base color).
const PALETTE_SATURATION: float = 1.0

## Brightness of the middle row (the base color).
const PALETTE_BRIGHTNESS: float = 1.0

## How far the topmost row is mixed toward white (0 = like the middle row).
const PALETTE_TINT: float = 0.8

## How far the bottommost row is mixed toward black (0 = like the middle row).
const PALETTE_SHADE: float = 0.8


## Palette column, in the same numbering the picker and the shader's
## `lpc_palette_cell_x` use.
@export_range(0, 16) var palette_cell_x: int = 0:
	set(value):
		if palette_cell_x != value:
			palette_cell_x = value
			emit_changed()

## Palette row, in the same numbering the picker and the shader's
## `lpc_palette_cell_y` use.
@export_range(0, 8) var palette_cell_y: int = 0:
	set(value):
		if palette_cell_y != value:
			palette_cell_y = value
			emit_changed()

## Which preset supplies roughness / metallic / clearcoat / emission.
@export var preset: Preset = Preset.SOLID:
	set(value):
		if preset != value:
			preset = value
			emit_changed()

## -1.0 keeps the preset's own emission; any other value overrides it. This is
## the lamp-on / lamp-off switch when two looks differ in nothing else.
@export_range(-1.0, 1.0) var emission_override: float = -1.0:
	set(value):
		if not is_equal_approx(emission_override, value):
			emission_override = value
			emit_changed()


## Push this look onto [param instance] -- a MeshInstance3D (or any other
## GeometryInstance3D) whose material is lpc_singlecolor.tres.
##
## Assigning that material is up to you (Material Override in the inspector, or
## your own code). If the instance runs a different shader, these writes go
## nowhere: nothing errors, the look simply has no effect.
##
## Cheap enough to call on every state change: four per-instance parameter
## writes, no material duplication, no shader recompile.
##
## The uniform names below are literal on purpose. They are part of the shader's
## own source text, not of the export's configurable namespace, so they do not
## follow the file-name prefix.
func apply_to(instance: GeometryInstance3D) -> void:
	instance.set_instance_shader_parameter(&"lpc_palette_cell_x", palette_cell_x)
	instance.set_instance_shader_parameter(&"lpc_palette_cell_y", palette_cell_y)
	instance.set_instance_shader_parameter(&"lpc_preset_position", preset)
	instance.set_instance_shader_parameter(&"lpc_emission_override", emission_override)


## The color of palette cell ([param x], [param y]) as an opaque [Color] --
## the palette carries no alpha, so it stays at 1.0.
##
## Computed from the PALETTE_* constants above, the same construction the
## add-on's own palette uses: column 0 is a white-to-black ramp when the
## palette has a greyscale column, the remaining columns split the color wheel
## evenly between them; the middle row is the base color, rows above it fan
## toward white by up to [constant PALETTE_TINT], rows below toward black by
## up to [constant PALETTE_SHADE].
##
## Static, because a palette is one per export and not per look:
## [code]LpcSinglecolorResource.color_at(2, 3)[/code] works
## without a resource in hand.
##
## Coordinates outside the grid clamp to the edge cell instead of erroring --
## the same thing the shader's `repeat_disable` sampler does with an
## out-of-range UV, so both ends of the pipeline agree on nonsense input.
##
## What comes back is a recomputation, not a texture read: expect the last
## digits to differ from what the shader samples out of
## lpc_palette.png, which is quantized to 8 bits per channel on its way
## through the PNG. Nothing an eye resolves, but do not compare the two for
## equality.
static func color_at(x: int, y: int) -> Color:
	var cx := clampi(x, 0, PALETTE_COLS - 1)
	var cy := clampi(y, 0, PALETTE_ROWS - 1)
	# 0.0 = top row (lightest) .. 1.0 = bottom row (darkest); a single-row
	# palette is all base color, hence the midpoint.
	var t := float(cy) / float(PALETTE_ROWS - 1) if PALETTE_ROWS > 1 else 0.5

	if PALETTE_HAS_GREYSCALE and cx == 0:
		var grey := 1.0 - t
		return Color(grey, grey, grey)

	# The greyscale column sits in front of the wheel, so it shifts the column
	# index and the number of hues to spread over by the same one.
	var wheel_start := 1 if PALETTE_HAS_GREYSCALE else 0
	var hue := float(cx - wheel_start) / float(PALETTE_COLS - wheel_start)
	var saturation := PALETTE_SATURATION
	var brightness := PALETTE_BRIGHTNESS
	if t <= 0.5:
		var row_factor := 1.0 - t / 0.5  # 1 = topmost .. 0 = middle
		saturation = PALETTE_SATURATION * (1.0 - PALETTE_TINT * row_factor)
		brightness = PALETTE_BRIGHTNESS + (1.0 - PALETTE_BRIGHTNESS) * PALETTE_TINT * row_factor
	else:
		var row_factor := (t - 0.5) / 0.5  # 0 = middle .. 1 = bottommost
		saturation = PALETTE_SATURATION + (1.0 - PALETTE_SATURATION) * PALETTE_SHADE * row_factor
		brightness = PALETTE_BRIGHTNESS * (1.0 - PALETTE_SHADE * row_factor)

	return Color.from_hsv(hue, clampf(saturation, 0.0, 1.0), clampf(brightness, 0.0, 1.0))


## This look's own color: [method color_at] for the cell stored in
## [member palette_cell_x] / [member palette_cell_y].
##
## For everything that should match the mesh without running the shader -- a UI
## swatch, a [Light3D] color, a particle modulate, a fade the tween drives.
## Note that this is the palette color alone; the preset's emission is not
## folded in, so a lamp look does not come back brighter here.
func get_color() -> Color:
	return color_at(palette_cell_x, palette_cell_y)
